In [ ]:
#libraries

import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/online_retail_II.csv')
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [ ]:
#Inspection

df.info()
df.describe()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482436 entries, 0 to 482435
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      482436 non-null  object
 1   StockCode    482436 non-null  object
 2   Description  479632 non-null  object
 3   Quantity     482436 non-null  int64
 4   InvoiceDate  482435 non-null  object
 5   Price        482435 non-null  float64
 6   Customer ID  386573 non-null  float64
 7   Country      482435 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 29.4+ MB

(482436, 8)

In [ ]:
#Rwemoving missing customerId

df = df.dropna(subset=['Customer ID'])

In [ ]:
# Removing negative Quantity

df = df[df['Quantity'] > 0]

In [ ]:
#Removing invalid prices

df = df[df['Price'] > 0]

In [ ]:
#Converting InvoiceDate to datetime
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

/tmp/ipykernel_3347/2120040342.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [ ]:
#Reset index

df = df.reset_index(drop=True)

In [ ]:
#Total Amount

df['TotalAmount'] = df['Quantity'] * df['Price']

In [ ]:
#Year

df['Year'] = df['InvoiceDate'].dt.year

In [ ]:
#Month

df['Month'] = df['InvoiceDate'].dt.month

In [ ]:
#Year - Month

df['YearMonth'] = df['InvoiceDate'].dt.to_period('M').astype(str)

In [ ]:
#day of week

df['DayOfWeek'] = df['InvoiceDate'].dt.day_name()

In [ ]:
#Validation

df.isnull().sum()
df.describe()

,Quantity,InvoiceDate,Price,Customer ID,TotalAmount,Year,Month
count,377362.000000,377362,377362.000000,377362.000000,377362.000000,377362.000000,377362.000000
mean,13.811115,2010-06-19 03:47:55.948558592,3.314980,15355.861200,21.763230,2009.918503,7.077456
min,1.000000,2009-12-01 07:45:00,0.001000,12346.000000,0.001000,2009.000000,1.000000
25%,2.000000,2010-03-19 13:22:00,1.250000,13983.000000,4.950000,2010.000000,4.000000
50%,5.000000,2010-06-24 12:11:00,1.950000,15311.000000,11.900000,2010.000000,7.000000
75%,12.000000,2010-09-30 17:47:00,3.750000,16795.000000,19.500000,2010.000000,10.000000
max,19152.000000,2010-11-23 13:02:00,10953.500000,18287.000000,15818.400000,2010.000000,12.000000
std,99.967520,NaN,36.106842,1675.756495,77.669107,0.273598,3.401217

In [ ]:
#Removing Duplicates

df = df.drop_duplicates()

In [ ]:
#Top countries

df['Country'].value_counts().head()

Country
United Kingdom    336942
EIRE                8260
Germany             7140
France              4962
Netherlands         2636
Name: count, dtype: int64

In [ ]:
#Saving the clean data

df.to_csv("cleaned_retail.csv", index=False)